### ISSUE TITLE
TODO LIST | READ

### ISSUE THREAD

**Issue by minnyoung** [minnyoung/wanted-pre-onboarding-frontend#4]
### 예시
![214471527-bd8037b9-f2dd-4db0-ade0-3d5ce27a6c0c](https://user-images.githubusercontent.com/118191378/229567429-a847cbac-61c7-4217-b374-80fa3afa787a.gif)

- [ ] `/todo`경로에 접속하면 투두 리스트의 목록을 볼 수 있도록 해주세요.
목록에서는 TODO의 내용과 완료 여부가 표시되어야 합니다.
- [ ] TODO의 완료 여부는 `<input type="checkbox" />`를 통해 표현해주세요
- [ ] TODO는 `<li>` tag를 이용해 감싸주세요
```js
<li>
  <label>
    <input type="checkbox" />
    <span>TODO 1</span>
  </label>
</li>
<li>
  <label>
    <input type="checkbox" />
    <span>TODO 2</span>
  </label>
</li>
```
