### ISSUE TITLE
TODO LIST | DELETE

### ISSUE THREAD

**Issue by minnyoung** [minnyoung/wanted-pre-onboarding-frontend#5]
### 예시
![214471527-bd8037b9-f2dd-4db0-ade0-3d5ce27a6c0c](https://user-images.githubusercontent.com/118191378/229567429-a847cbac-61c7-4217-b374-80fa3afa787a.gif)

- [ ] TODO 우측에 수정버튼과 삭제 버튼을 만들어주세요
- [ ] 수정 버튼에는 data-testid="modify-button" 속성을 부여해주세요
- [ ] 삭제 버튼에는 data-testid="delete-button" 속성을 부여해주세요

```js
<li>
  <label>
    <input type="checkbox" />
    <span>TODO 1</span>
  </label>
  <button data-testid="modify-button">수정</button>
  <button data-testid="delete-button">삭제</button>
</li>
```

- [ ] 투두 리스트의 삭제 기능을 구현해주세요
- [ ] 투두 리스트의 TODO 우측의 삭제버튼을 누르면 해당 아이템이 삭제되도록 해주세요
